# Generated by Django 4.1.6 on 2023-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('veggie', models.BooleanField()),
                ('soy', models.BooleanField()),
                ('eggs', models.BooleanField()),
                ('milk', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('gluten', models.BooleanField()),
                ('halal', models.BooleanField()),
                ('unknown', models.BooleanField()),
                ('time', models.BooleanField()),
            ],
        ),
    ]
