# Generated by Django 4.1.6 on 2023-02-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodItems',
            new_name='foodItem',
        ),
    ]
